name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
          sudo apt install -y libopenmpi-dev openmpi-bin gfortran
          git clone https://github.com/libocca/occa
          cd occa
          make -j `nproc`
          cd ..
    - name: Build
      run: make -j `nproc`
      env: 
        OCCA_DIR: ${GITHUB_WORKSPACE}/occa
        LD_LIBRARY_PATH: ${GITHUB_WORKSPACE}/occa/lib
    - name: Test
      run: |
        echo ${LD_LIBRARY_PATH}
        ls ${OCCA_DIR}/lib
        make test
      env: 
        OCCA_DIR: ${GITHUB_WORKSPACE}/occa
        LD_LIBRARY_PATH: ${GITHUB_WORKSPACE}/occa/lib
